groups:
  - name: groovy-hikaricp-alerts
    rules:
    - alert: HikariCpuPoolPendingDetected
      expr: 1
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "HikariCP Pool Pending Detected!"
        description: "Severe connection delay on backend database."

    - alert: BackendMemoryUsageTooHigh
      expr: (sum(jvm_memory_used_bytes{area="heap"}) / sum(jvm_memory_max_bytes{area="heap"})) > 0.4
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: "Backend JVM Heap Usage Over 40%!"
        description: "JVM Heap memory usage has exceeded 40%."
    - alert: BackendCpuSpikeDetected
      expr: 1
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: "Backend CPU Spike Over 95%!"
        description: "High CPU utilization on backend container."

